# vim:ft=kitty
include theme.conf
font_family family='Ioskeley Mono' features='-calt'
symbol_map U+E000-U+F8FF Symbols Nerd Font
font_size 12

background_opacity 0.75
# background_blur 1
tab_bar_style powerline
tab_title_max_length 32

hide_window_decorations yes
remember_window_size no
window_border_width 1pt
underline_hyperlinks always
