style = "compact"
filter_mode = "session-preload"
inline_height = 14
show_tabs = false
store_failed = false
enter_accept = true

auto_sync = false
update_check = false

[stats]

[sync]
records = false

[keys]

[preview]

[daemon]

[logs]
enabled = false

[theme]

[ui]
