# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# Theme
export ZSH_THEME="custom"

# How often to auto-update (in days).
zstyle ':omz:update' frequency 7

# DISABLE_MAGIC_FUNCTIONS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Autosuggestions configuration
bindkey '^[[1;5C' forward-word
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(end-of-line)
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(forward-char forward-word)

# Plugins
plugins=(git aws zsh-autosuggestions)

# Oh my zsh
source $ZSH/oh-my-zsh.sh

# Configuration
export XDG_CONFIG_HOME="$HOME/.config"
export EDITOR="nvim"
export TAILSCALE_EXIT_NODE="us-mia-wg-003.mullvad.ts.net."

# fzf god
# source <(fzf --zsh)

# Atuin god
unset HISTFILE
HISTSIZE=0
SAVEHIST=0
eval "$(atuin init zsh)"

# Node
eval "$(fnm env --use-on-cd --shell zsh)"
export PNPM_HOME="$HOME/.pnpm"

# herdr
eval "$(herdr completions zsh)"

# Path
path+=$HOME/.local/bin
path+=$HOME/.pnpm/bin
path+=$HOME/.cargo/bin
path+=$HOME/go/bin
